apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obmondo-k8s-agent.fullname" . }}
  labels:
    {{- include "obmondo-k8s-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "obmondo-k8s-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obmondo-k8s-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # - name: DURATION
            #   value: {{ .Values.envVars.Duration | default "5m0s" }}
            - name: ORPHANED_RES_DURATION
              value: {{ .Values.envVars.Duration | default "5m0s" }}
            - name: AGENT_CERT_PATH
              value: {{ .Values.envVars.certPath | default "tls.crt" }}
            - name: AGENT_KEY_PATH
              value: {{ .Values.envVars.keyPath | default "tls.key" }}
            - name: PROMETHEUS_URL
              value: {{ .Values.envVars.prometheusURL | default "http://localhost:9090" }}
            # - name: API_URL
            #   value: {{ .Values.envVars.apiURL | default "https://api.obmondo.com/api/clusters/node-count/" }}
          # {{- with .Values.image.volumeMounts}}
          # volumeMounts:
          #   {{- toYaml . | nindent 12}}
          # {{- end }}
          livenessProbe:
            exec:
              command:
              - ps
              - p1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 600
            initialDelaySeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      # {{- with .Values.volumes }}
      # volumes:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
